### ISSUE TITLE
pyzbar 库一直报错

### ISSUE THREAD

**Issue by lin-bin** [TechXueXi/TechXueXi#123]
![image](https://user-images.githubusercontent.com/57790037/144390324-f8e5cf09-51e6-49f3-a90e-f51e5943f01d.png)

**Comment by mszxylj** [comment]
先安装库。。

**Comment by lin-bin** [comment]
> 
我装了的，我在4台电脑上测试过，同样的代码，另外三台电脑都能成功运行，唯独我的笔记本一直在报pyzbar这个库的错，这个库重装了几次也不行

**Comment by mszxylj** [comment]
你安装的时候有没有报错？ 可能你笔记本安装过多个版本的python，系统环境变量没有改。去确定一下系统环境变量里的python路径


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 中午12:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] pyzbar 库一直报错 (Issue #123)





   
我装了的，我在4台电脑上测试过，同样的代码，另外三台电脑都能成功运行，唯独我的笔记本一直在报pyzbar这个库的错，这个库重装了几次也不行
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lin-bin** [comment]
> 你安装的时候有没有报错？可能你笔记本安装了几个版本的python，系统环境变量没有改。去确定一下系统环境变量的python路径
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "TechXueXi/TechXueXi " ***@***.***>; 发送时间： 2021年12月7日(星期二)中午12:01 ***@***.***>; ***@***.********@***.***>; 主题： Re：[TechXueXi/TechXueXi] pyzbar 库一直报错（Issue #123）我装了的，我在4台电脑上测试过，同样的代码，另外三台电脑可以成功运行，唯独我这个笔记本一直在报pyzbar的错，这个库重装库了几次也不行——你收到这个是因为你评论了。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

安装没有任何报错，我把pyzbar这个库卸载了，直接运行，就提示我缺少库是否自动安装，自动安装完重新运行就还是会报 pyzbar 这个库的错。
![image](https://user-images.githubusercontent.com/57790037/144964523-b97612fe-3cf8-42ac-a419-1927de40239e.png)

**Comment by lin-bin** [comment]
我笔记本就一个python环境，因为这个错误，还卸载过进行重装，还是有这个错误

**Comment by lin-bin** [comment]
![image](https://user-images.githubusercontent.com/57790037/144999072-1a487ac3-e613-49d6-83e0-b449e04bb78e.png)
![image](https://user-images.githubusercontent.com/57790037/144999097-9b7aa907-4e0e-4db0-9298-c314f12c256e.png)
一直报这个错误，这个库卸载重装也不行，我从能运行的电脑上，把这个库拷贝过来，运行还是报一样的错误

**Comment by forpw2009** [comment]
亲，您的邮件我收到啦！

**Comment by mszxylj** [comment]
https://blog.csdn.net/alanguoo/article/details/83782958
试试这个，安装一下VC库，这个应该能解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] pyzbar 库一直报错 (Issue #123)





 

 
 一直报这个错误，这个库卸载重装也不行，我从能运行的电脑上，把这个库拷贝过来，运行还是报一样的错误
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mszxylj** [comment]
https://www.cnblogs.com/Zhan-W/p/14906951.html
我在看这篇资料的时候看到的。python报错信息有点存在误导性。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] pyzbar 库一直报错 (Issue #123)





 

 
 一直报这个错误，这个库卸载重装也不行，我从能运行的电脑上，把这个库拷贝过来，运行还是报一样的错误
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lin-bin** [comment]
> https://www.cnblogs.com/Zhan-W/p/14906951.html 我在看这篇资料的时候看到的。python报错信息有点存在误导性。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TechXueXi/TechXueXi" ***@***.***&gt;; 发送时间:&nbsp;2021年12月7日(星期二) 下午5:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [TechXueXi/TechXueXi] pyzbar 库一直报错 (Issue #123) 一直报这个错误，这个库卸载重装也不行，我从能运行的电脑上，把这个库拷贝过来，运行还是报一样的错误 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

安装完后果然可以运行了，十分感谢。

**Comment by forpw2009** [comment]
亲，您的邮件我收到啦！
